<?php
    if(function_exists("register_field_group")) {
        $arraytitlevacancy = array();
        $arraykeytitlevacancy = array();
        $the_loop = null;
        $args = array   (
                            'post_type'        => 'vacancy',
                            'post_status'      => 'publish',
                        );
        $the_loop = get_posts($args);
        foreach ($the_loop as $key => $value) {
            array_push($arraytitlevacancy,$value->post_title);
            array_push($arraykeytitlevacancy,$value->post_title);
        }
        $array_combined = array_combine($arraykeytitlevacancy,$arraytitlevacancy);
        register_field_group(array (
            'id' => 'acf_candidate',
            'title' => 'Candidate',
            'fields' => array (
                array (
                    'key' => 'field_5c22fd113e5b8',
                    'label' => 'Name Candidate',
                    'name' => 'candidate_name',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Candidate Name',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5c22fd3d3e5b9',
                    'label' => 'Location Candidate',
                    'name' => 'location',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Location',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5c22fd6d3e5ba',
                    'label' => 'Experience Candidate',
                    'name' => 'experience',
                    'type' => 'number',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Experience',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array (
                    'key' => 'field_5c22fd823e5bb',
                    'label' => 'Desired Salary Of Candidate',
                    'name' => 'desired_salary',
                    'type' => 'number',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Desired Salary',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array (
                    'key' => 'field_5c23ad823e5bb',
                    'label' => 'Applied Position Of Candidate',
                    'name' => 'applied_position',
                    'type' => 'select',
                    'choices' => $array_combined,
                    'default_value' => '',
                    'allow_null' => 0,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_5c22fdbc3e5bc',
                    'label' => 'Stage',
                    'name' => 'stage',
                    'type' => 'select',
                    'choices' => array (
                        'Screening' => 'Screening',
                        'Phone Interview' => 'Phone Interview',
                        'In-office Interview' => 'In-office Interview',
                        'Make an offer' => 'Make an offer',
                    ),
                    'default_value' => 'Screening',
                    'allow_null' => 0,
                    'multiple' => 0,
                ),
                array (
                    'key' => 'field_5c22fdcb3e5bd',
                    'label' => 'Phone of Candidate',
                    'name' => 'tel',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Tel',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5c22fde53e5be',
                    'label' => 'Email Candidate',
                    'name' => 'email',
                    'type' => 'email',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Email',
                    'prepend' => '',
                    'append' => '',
                ),
                array (
                    'key' => 'field_5c22fdf43e5bf',
                    'label' => 'Facebook link Candidate',
                    'name' => 'social_link',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Social Link',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5c24sqf43e5bf',
                    'label' => 'Linkendin link Candidate',
                    'name' => 'social_link_linkendin',
                    'type' => 'text',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Social Link Linkendin',
                    'prepend' => '',
                    'append' => '',
                    'formatting' => 'html',
                    'maxlength' => '',
                ),
                array (
                    'key' => 'field_5c22fe1a3e5c0',
                    'label' => 'CV pdf',
                    'name' => 'cv',
                    'type' => 'file',
                    'required' => 0,
                    'save_format' => 'object',
                    'library' => 'all',
                ),
                array (
                    'key' => 'field_5c22fe513e5c1',
                    'label' => 'total Rating Candidate',
                    'name' => 'rating',
                    'type' => 'number',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Rating',
                    'prepend' => '',
                    'append' => '',
                    'min' => '',
                    'max' => '',
                    'step' => '',
                ),
                array (
                    'key' => 'field_5c22fe613e5c2',
                    'label' => 'Comment',
                    'name' => 'commentbyauthor',
                    'type' => 'textarea',
                    'required' => 0,
                    'default_value' => '',
                    'placeholder' => 'Comment by author',
                    'maxlength' => '',
                    'rows' => '',
                    'formatting' => 'br',
                ),
            ),
            'location' => array (
                array (
                    array (
                        'param' => 'post_type',
                        'operator' => '==',
                        'value' => 'candidate',
                        'order_no' => 0,
                        'group_no' => 0,
                    ),
                ),
            ),
            'options' => array (
                'position' => 'normal',
                'layout' => 'no_box',
                'hide_on_screen' => array (
                    0 => 'the_content',
                    1 => 'excerpt',
                    2 => 'custom_fields',
                    3 => 'discussion',
                    4 => 'revisions',
                    5 => 'author',
                    6 => 'format',
                    7 => 'categories',
                    8 => 'tags',
                    9 => 'send-trackbacks',
                ),
            ),
            'menu_order' => 0,
        ));
    }
?>